language: python
python:
  - "3.5"
  - "3.6"

install:
  # Install test requirements seperately
  - pip install -q pytest pytest-runner pytest-cov coverage python-coveralls
  - python setup.py install

script:
  - pytest

after_success:
  - COVERALLS_REPO_TOKEN=kQuX1Zr77YwYiNEmRuPUqWPPfjmNTh593 coveralls