language: python
python:
  - "2.7"
  - "3.5"
  - "3.6"

install:
  # Install test requirements seperately
  - pip install -q pytest pytest-runner pytest-cov coverage
  - python setup.py install

script:
  - pytest