name: earthchem
channels:
  - conda-forge
dependencies:
  - numpy
  - pandas
  - scikit-learn
  - geopandas
  - requests
  - pytest
  - coverage
  - ipykernel
  - owslib
  - geojson
  - cartopy
  - pyyaml
  - periodictable
  - python-ternary
  - pip:
    - versioneer
    - pytest-cov
    - pytest-runner
    - nbdime
    - nbstripout
    - --editable=.
