name: earthchem
channels:
  - conda-forge
dependencies:
  - numpy
  - pandas
  - geopandas
  - requests
  - pytest
  - coverage
  - ipykernel
  - owslib
  - geojson
  - cartopy
  - pyyaml
  - pip:
    - periodictable
    - python-ternary
    - versioneer
    - pytest-cov
    - pytest-runner
    - nbdime
    - nbstripout
    - --editable=.
